/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBankRouteImport } from './routes/app.bank'
import { Route as AppBookRouteImport } from './routes/app.book'
import { Route as AppCentresRouteImport } from './routes/app.centres'
import { Route as AppComplaintRouteImport } from './routes/app.complaint'
import { Route as AppFaqRouteImport } from './routes/app.faq'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppLanguageRouteImport } from './routes/app.language'
import { Route as AppMoreRouteImport } from './routes/app.more'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppPaymentRouteImport } from './routes/app.payment'
import { Route as AppPaymentsCompletedRouteImport } from './routes/app.payments-completed'
import { Route as AppProcurementRouteImport } from './routes/app.procurement'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppQueueRouteImport } from './routes/app.queue'
import { Route as AppTokenRouteImport } from './routes/app.token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBankRoute = AppBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AppRoute,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AppRoute,
} as any)
const AppCentresRoute = AppCentresRouteImport.update({
  id: '/centres',
  path: '/centres',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintRoute = AppComplaintRouteImport.update({
  id: '/complaint',
  path: '/complaint',
  getParentRoute: () => AppRoute,
} as any)
const AppFaqRoute = AppFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppLanguageRoute = AppLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentRoute = AppPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsCompletedRoute = AppPaymentsCompletedRouteImport.update({
  id: '/payments-completed',
  path: '/payments-completed',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementRoute = AppProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppTokenRoute = AppTokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/bank': typeof AppBankRoute
  '/app/book': typeof AppBookRoute
  '/app/centres': typeof AppCentresRoute
  '/app/complaint': typeof AppComplaintRoute
  '/app/faq': typeof AppFaqRoute
  '/app/history': typeof AppHistoryRoute
  '/app/language': typeof AppLanguageRoute
  '/app/more': typeof AppMoreRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payment': typeof AppPaymentRoute
  '/app/payments-completed': typeof AppPaymentsCompletedRoute
  '/app/procurement': typeof AppProcurementRoute
  '/app/profile': typeof AppProfileRoute
  '/app/queue': typeof AppQueueRoute
  '/app/token': typeof AppTokenRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/bank': typeof AppBankRoute
  '/app/book': typeof AppBookRoute
  '/app/centres': typeof AppCentresRoute
  '/app/complaint': typeof AppComplaintRoute
  '/app/faq': typeof AppFaqRoute
  '/app/history': typeof AppHistoryRoute
  '/app/language': typeof AppLanguageRoute
  '/app/more': typeof AppMoreRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payment': typeof AppPaymentRoute
  '/app/payments-completed': typeof AppPaymentsCompletedRoute
  '/app/procurement': typeof AppProcurementRoute
  '/app/profile': typeof AppProfileRoute
  '/app/queue': typeof AppQueueRoute
  '/app/token': typeof AppTokenRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/bank': typeof AppBankRoute
  '/app/book': typeof AppBookRoute
  '/app/centres': typeof AppCentresRoute
  '/app/complaint': typeof AppComplaintRoute
  '/app/faq': typeof AppFaqRoute
  '/app/history': typeof AppHistoryRoute
  '/app/language': typeof AppLanguageRoute
  '/app/more': typeof AppMoreRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payment': typeof AppPaymentRoute
  '/app/payments-completed': typeof AppPaymentsCompletedRoute
  '/app/procurement': typeof AppProcurementRoute
  '/app/profile': typeof AppProfileRoute
  '/app/queue': typeof AppQueueRoute
  '/app/token': typeof AppTokenRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/language'
    | '/login'
    | '/register'
    | '/app/bank'
    | '/app/book'
    | '/app/centres'
    | '/app/complaint'
    | '/app/faq'
    | '/app/history'
    | '/app/language'
    | '/app/more'
    | '/app/notifications'
    | '/app/payment'
    | '/app/payments-completed'
    | '/app/procurement'
    | '/app/profile'
    | '/app/queue'
    | '/app/token'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/language'
    | '/login'
    | '/register'
    | '/app/bank'
    | '/app/book'
    | '/app/centres'
    | '/app/complaint'
    | '/app/faq'
    | '/app/history'
    | '/app/language'
    | '/app/more'
    | '/app/notifications'
    | '/app/payment'
    | '/app/payments-completed'
    | '/app/procurement'
    | '/app/profile'
    | '/app/queue'
    | '/app/token'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/language'
    | '/login'
    | '/register'
    | '/app/bank'
    | '/app/book'
    | '/app/centres'
    | '/app/complaint'
    | '/app/faq'
    | '/app/history'
    | '/app/language'
    | '/app/more'
    | '/app/notifications'
    | '/app/payment'
    | '/app/payments-completed'
    | '/app/procurement'
    | '/app/profile'
    | '/app/queue'
    | '/app/token'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LanguageRoute: typeof LanguageRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bank': {
      id: '/app/bank'
      path: '/bank'
      fullPath: '/app/bank'
      preLoaderRoute: typeof AppBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/book': {
      id: '/app/book'
      path: '/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/centres': {
      id: '/app/centres'
      path: '/centres'
      fullPath: '/app/centres'
      preLoaderRoute: typeof AppCentresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/complaint': {
      id: '/app/complaint'
      path: '/complaint'
      fullPath: '/app/complaint'
      preLoaderRoute: typeof AppComplaintRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/faq': {
      id: '/app/faq'
      path: '/faq'
      fullPath: '/app/faq'
      preLoaderRoute: typeof AppFaqRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/language': {
      id: '/app/language'
      path: '/language'
      fullPath: '/app/language'
      preLoaderRoute: typeof AppLanguageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/more': {
      id: '/app/more'
      path: '/more'
      fullPath: '/app/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payment': {
      id: '/app/payment'
      path: '/payment'
      fullPath: '/app/payment'
      preLoaderRoute: typeof AppPaymentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments-completed': {
      id: '/app/payments-completed'
      path: '/payments-completed'
      fullPath: '/app/payments-completed'
      preLoaderRoute: typeof AppPaymentsCompletedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/procurement': {
      id: '/app/procurement'
      path: '/procurement'
      fullPath: '/app/procurement'
      preLoaderRoute: typeof AppProcurementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/queue': {
      id: '/app/queue'
      path: '/queue'
      fullPath: '/app/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/token': {
      id: '/app/token'
      path: '/token'
      fullPath: '/app/token'
      preLoaderRoute: typeof AppTokenRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBankRoute: typeof AppBankRoute
  AppBookRoute: typeof AppBookRoute
  AppCentresRoute: typeof AppCentresRoute
  AppComplaintRoute: typeof AppComplaintRoute
  AppFaqRoute: typeof AppFaqRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLanguageRoute: typeof AppLanguageRoute
  AppMoreRoute: typeof AppMoreRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPaymentRoute: typeof AppPaymentRoute
  AppPaymentsCompletedRoute: typeof AppPaymentsCompletedRoute
  AppProcurementRoute: typeof AppProcurementRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQueueRoute: typeof AppQueueRoute
  AppTokenRoute: typeof AppTokenRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBankRoute: AppBankRoute,
  AppBookRoute: AppBookRoute,
  AppCentresRoute: AppCentresRoute,
  AppComplaintRoute: AppComplaintRoute,
  AppFaqRoute: AppFaqRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLanguageRoute: AppLanguageRoute,
  AppMoreRoute: AppMoreRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPaymentRoute: AppPaymentRoute,
  AppPaymentsCompletedRoute: AppPaymentsCompletedRoute,
  AppProcurementRoute: AppProcurementRoute,
  AppProfileRoute: AppProfileRoute,
  AppQueueRoute: AppQueueRoute,
  AppTokenRoute: AppTokenRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LanguageRoute: LanguageRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
